// Generated by `nu scripts/ocmts.nu matrix gen cypress`.
// Do not edit by hand.
export const matrixCellIds = [
  "contact-token__cernbox-v11__cernbox-v11",
  "contact-token__cernbox-v11__nextcloud-v35",
  "contact-token__cernbox-v11__ocis-v8",
  "contact-token__cernbox-v11__opencloud-v6",
  "contact-token__nextcloud-v35__cernbox-v11",
  "contact-token__nextcloud-v35__nextcloud-v35",
  "contact-token__nextcloud-v35__ocis-v8",
  "contact-token__nextcloud-v35__opencloud-v6",
  "contact-token__ocis-v8__cernbox-v11",
  "contact-token__ocis-v8__nextcloud-v35",
  "contact-token__ocis-v8__ocis-v8",
  "contact-token__ocis-v8__opencloud-v6",
  "contact-token__opencloud-v6__cernbox-v11",
  "contact-token__opencloud-v6__nextcloud-v35",
  "contact-token__opencloud-v6__ocis-v8",
  "contact-token__opencloud-v6__opencloud-v6",
] as const;
export type MatrixCellId = (typeof matrixCellIds)[number];
