image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    # Docker helper extension.
    - ms-azuretools.vscode-docker

    # PHP extension.
    - felixfbecker.php-debug

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

    # Env file highlight.
    - mikestead.dotenv

    # Github Theme.
    - github.github-vscode-theme

    # Python.
    - ms-python.python
    - charliermarsh.ruff

    # toml
    - bungcip.better-toml

# Define Ports and how they should be handled
# Documentation: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 5800
    onOpen: ignore
    visibility: public
    name: firefox
    description: firefox used by devstock to test Pondersource apps in browser
  - port: 5900
    onOpen: ignore
    visibility: public
    name: firefox legacy
    description: firefox used by devstock to test Pondersource apps in browser
  - port: 9003
    onOpen: ignore
    visibility: public
    name: Nextcloud Xdebug
    description: Xdebug client port.

tasks:
  - init: chmod +x ./scripts/init-gitpod-prebuild.sh && ./scripts/init-gitpod-prebuild.sh
