image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    # Docker helper extension.
    - ms-azuretools.vscode-docker

    # PHP extension.
    - felixfbecker.php-debug

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

    # Env file highlight.
    - mikestead.dotenv

    # Github Theme.
    - github.github-vscode-theme

    # Python.
    - ms-python.python
    - charliermarsh.ruff

    # toml
    - tamasfe.even-better-toml

# Define Ports and how they should be handled
# Documentation: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 4501
    onOpen: ignore
    visibility: public
  - port: 4502
    onOpen: ignore
    visibility: public
  - port: 4503
    onOpen: ignore
    visibility: public
  - port: 4504
    onOpen: ignore
    visibility: public
  - port: 4505
    onOpen: ignore
    visibility: public
  - port: 4506
    onOpen: ignore
    visibility: public
  - port: 5700
    onOpen: ignore
    visibility: public
    name: VNC
    description: VNC server to view Cypress.
  - port: 5800
    onOpen: ignore
    visibility: public
    name: FireFox
    description: Embedded browser to access docker containers.
  - port: 9003
    onOpen: ignore
    visibility: public
    name: Xdebug
    description: Xdebug client port.

tasks:
  - init: chmod +x ./init/prebuild.sh && ./init/prebuild.sh
