stages:
  - test

.parallel-hidden-job:
  parallel:
    matrix:
      - BROWSER: [chrome, edge, firefox, electron]
  
ocm-test-suite:
  extends: .parallel-hidden-job
  stage: test
  image: docker
  services: 
    - docker:dind
  script:
    - apk add bash
    - apk add git
    - ./docker/pull/ocm-test-suite.sh
    - ./init/ocm-test-suite.sh
    - ./dev/ocm-test-suite.sh ci $BROWSER
  artifacts:
    paths:
      - ./cypress/ocm-tests/cypress/videos
    expire_in: 1 week
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "ocm"'
