name: Nextcloud CI Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: nextcloud
          MYSQL_PASSWORD: nextcloud
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: nextcloud
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      nextcloud:
        image: pondersource/nextcloud-ci:latest
        env:
          # CI-specific environment variables
          NEXTCLOUD_REPO_URL: https://github.com/nextcloud/server
          NEXTCLOUD_BRANCH: ${{ github.ref_name }}
          NEXTCLOUD_COMMIT_HASH: ${{ github.sha }}
          
          # Standard Nextcloud environment variables
          MYSQL_HOST: db
          MYSQL_PASSWORD: nextcloud
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: nextcloud
          REDIS_HOST: redis
          NEXTCLOUD_ADMIN_USER: admin
          NEXTCLOUD_ADMIN_PASSWORD: admin
          NEXTCLOUD_TRUSTED_DOMAINS: localhost:8080
          HOST: localhost
        ports:
          - 8080:80
        options: --health-cmd="curl --fail http://localhost:80/status.php || exit 1" --health-interval=60s --health-timeout=10s --health-retries=5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Wait for Nextcloud to be ready
        run: |
          echo "Waiting for Nextcloud to be ready..."
          timeout 300 bash -c 'until curl -s http://localhost:8080/status.php | grep -q "installed":true; do sleep 5; done'
          echo "Nextcloud is ready!"
      
      - name: Run tests
        run: |
          # Add your test commands here
          curl -s http://localhost:8080/status.php
          
          # Example: Run PHPUnit tests
          # docker exec nextcloud php -f /var/www/html/occ app:enable your_app
          # docker exec nextcloud cd /var/www/html/apps/your_app && ./vendor/bin/phpunit 