# Generated by: {{placeholder:generator.command}}
# Do NOT edit by hand - regenerate with the command above.

name: OCM Test Suite CI

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:
    inputs:
      suite-id:
        description: 'Override suite_id for this run'
        required: false
        default: ''

jobs:
  preflight:
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Workflow drift check
        env:
          OCMTS_ROOT: ${{ github.workspace }}
        run: nu scripts/ocmts.nu ci workflows check github
      - name: Adapter capabilities drift check
        env:
          OCMTS_ROOT: ${{ github.workspace }}
        run: nu scripts/ocmts.nu matrix check capabilities

  setup:
    needs: [preflight]
    runs-on: {{placeholder:runner.label}}
    outputs:
      suite-id: ${{ steps.gen.outputs['suite-id'] }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Generate suite ID
        id: gen
        run: |
          if [ -n "${{ inputs['suite-id'] }}" ]; then
            SUITE_ID=$(nu scripts/ocmts.nu ci suite-id --override "${{ inputs['suite-id'] }}")
          else
            SUITE_ID=$(nu scripts/ocmts.nu ci suite-id)
          fi
          echo "suite-id=$SUITE_ID" >> $GITHUB_OUTPUT
{{placeholder:flow.jobs}}

  aggregate:
{{placeholder:aggregate.needs.block}}
    if: always() && needs.setup.result == 'success'
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Download all cell artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: 'cell-*'
          merge-multiple: true
      - name: Aggregate suite manifest
        run: |
          EXPECTED=$(nu scripts/ocmts.nu ci plan --cell-ids)
          nu scripts/ocmts.nu ci plan --capability-skipped-json artifacts/capability-skipped-cells.json
          nu scripts/ocmts.nu ci find-suite-dirs artifacts > artifacts/suite-dirs.txt
          nu scripts/ocmts.nu ci aggregate \
            --suite-id "${{ needs.setup.outputs['suite-id'] }}" \
            --output-dir artifacts/suites/aggregated \
            --expected-cells "$EXPECTED" \
            --capability-skipped-cells artifacts/capability-skipped-cells.json \
            --dirs-file artifacts/suite-dirs.txt \
            --archive
      - name: Upload aggregate outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aggregate-summary
          path: artifacts/suites/aggregated/
          if-no-files-found: warn

  ci-site:
    needs: [aggregate]
    if: github.ref == 'refs/heads/{{placeholder:publish.branch.gate}}' && needs.aggregate.result == 'success'
    uses: ./.github/workflows/{{placeholder:site.workflow.filename}}
    with:
      source-run-id: ${{ github.run_id }}
