# Generated by: {{placeholder:generator.command}}
# Do NOT edit by hand - regenerate with the command above.

name: OCM Test Suite CI

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:
    inputs:
      suite-id:
        description: 'Override suite_id for this run'
        required: false
        default: ''

jobs:
  preflight:
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Adapter capabilities drift check
        env:
          OCMTS_ROOT: ${{ github.workspace }}
        run: nu scripts/ocmts.nu matrix check capabilities

  setup:
    needs: [preflight]
    runs-on: {{placeholder:runner.label}}
    outputs:
      suite-id: ${{ steps.gen.outputs['suite-id'] }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Generate suite ID
        id: gen
        run: |
          SUITE_ID="${{ inputs['suite-id'] }}"
          if [ -z "$SUITE_ID" ]; then
            SUITE_ID=$(nu -c "use scripts/lib/suite/index.nu [new-suite-id]; new-suite-id | print")
          fi
          echo "suite-id=$SUITE_ID" >> $GITHUB_OUTPUT
{{placeholder:flow.jobs}}

  aggregate:
{{placeholder:aggregate.needs.block}}
    if: always() && needs.setup.result == 'success'
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Download all cell artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: 'cell-*'
          merge-multiple: true
      - name: Aggregate suite manifest
        run: |
          EXPECTED=$(nu scripts/ocmts.nu ci plan --cell-ids)
          CAP_SKIPPED_JSON=artifacts/capability-skipped-cells.json
          nu scripts/ocmts.nu ci plan | jq '[.cells[] | select(.capability_action == "capability-skipped") | {
            cell_id,
            flow_id,
            pair,
            scenario,
            artifact_name,
            execution_id,
            sender_platform,
            sender_version,
            receiver_platform,
            receiver_version,
            browser,
            is_two_party,
            capability_skip
          }]' > "$CAP_SKIPPED_JSON"
          nu scripts/ocmts.nu ci aggregate \
            --suite-id "${{ needs.setup.outputs['suite-id'] }}" \
            --output-dir artifacts/suites/aggregated \
            --expected-cells "$EXPECTED" \
            --capability-skipped-cells "$CAP_SKIPPED_JSON" \
            --archive \
            $(find artifacts -name 'suite-manifest.v1.json' -printf '%h ')
      - name: Upload aggregate outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aggregate-summary
          path: artifacts/suites/aggregated/
          if-no-files-found: warn

  ci-site:
    needs: [aggregate]
    if: github.ref == 'refs/heads/{{placeholder:publish.branch.gate}}' && needs.aggregate.result == 'success'
    uses: ./.github/workflows/{{placeholder:site.workflow.filename}}
    with:
      source-run-id: ${{ github.run_id }}
