# Generated by: {{placeholder:generator.command}}
# Do NOT edit by hand - regenerate with the command above.

name: OCM Test Suite CI

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:
    inputs:
      suite-id:
        description: 'Override suite_id for this run'
        required: false
        default: ''

jobs:
  setup:
    runs-on: {{placeholder:runner.label}}
    outputs:
      suite-id: ${{ steps.gen.outputs['suite-id'] }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Generate suite ID
        id: gen
        run: |
          SUITE_ID="${{ inputs['suite-id'] }}"
          if [ -z "$SUITE_ID" ]; then
            SUITE_ID=$(nu -c "use scripts/lib/suite-index.nu [new-suite-id]; new-suite-id | print")
          fi
          echo "suite-id=$SUITE_ID" >> $GITHUB_OUTPUT
{{placeholder:flow.jobs}}

  aggregate:
{{placeholder:aggregate.needs.block}}
    if: always() && needs.setup.result == 'success'
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Download all cell artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: 'cell-*'
          merge-multiple: true
      - name: Aggregate suite manifest
        run: |
          EXPECTED=$(nu scripts/ocmts.nu ci plan --cell-ids)
          nu scripts/ocmts.nu ci aggregate \
            --suite-id "${{ needs.setup.outputs['suite-id'] }}" \
            --output-dir artifacts/suites/aggregated \
            --expected-cells "$EXPECTED" \
            --archive \
            $(find artifacts -name 'suite-manifest.v1.json' -printf '%h ')
      - name: Upload aggregate outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aggregate-summary
          path: artifacts/suites/aggregated/
          if-no-files-found: warn

  site-publish:
    needs: [aggregate]
    if: github.ref == 'refs/heads/main' && needs.aggregate.result == 'success'
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Download aggregate bundle
        uses: actions/download-artifact@v4
        with:
          name: aggregate-summary
          path: artifacts/suites/aggregated/
      - name: Extract aggregate archive
        run: |
          tar -x -I zstd -f artifacts/suites/aggregated/suite-artifacts.tar.zst
      - name: Publish site
        env:
          OCMTS_SITE_REPO_SLUG: ${{ vars.OCMTS_SITE_REPO_SLUG || '' }}
          OCMTS_SITE_REF: ${{ vars.OCMTS_SITE_REF || 'main' }}
          OCMTS_SITE_REPO_URL: ${{ vars.OCMTS_SITE_REPO_URL || '' }}
        run: nu scripts/ocmts.nu site publish --artifacts-root artifacts --latest-suite
