# Generated by: {{placeholder:generator.command}}
# Do NOT edit by hand - regenerate with the command above.
# Reusable workflow: each matrix cell calls this.

name: Run OCM Test Cell

on:
  workflow_call:
    inputs:
      scenario:
        required: true
        type: string
      sender-platform:
        required: true
        type: string
      sender-version:
        required: true
        type: string
      receiver-platform:
        required: false
        type: string
        default: ''
      receiver-version:
        required: false
        type: string
        default: ''
      suite-id:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      cell-id:
        required: true
        type: string
      failure-reason:
        required: false
        type: string
        default: ''
      cell-depends-on:
        required: false
        type: string
        default: ''
    outputs:
      cell-status:
        description: 'Cell execution status: passed, failed, or blocked'
        value: ${{ jobs['run-cell'].outputs['cell-status'] }}

jobs:
  run-cell:
    runs-on: {{placeholder:runner.label}}
    outputs:
      cell-status: ${{ steps.run_cell.outputs['cell-status'] || steps.blocked_cell.outputs['cell-status'] || 'failed' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Generate execution ID
        id: cell
        run: |
          EXEC_ID=$(nu -c "use scripts/lib/run/execution-id.nu [new-execution-id]; new-execution-id | print")
          echo "execution-id=$EXEC_ID" >> $GITHUB_OUTPUT
      - name: Download prerequisite artifacts
        id: prereq_dl
        if: inputs['cell-depends-on'] != '' && inputs['failure-reason'] == ''
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          IFS=',' read -ra DEPS <<< "${{ inputs['cell-depends-on'] }}"
          for dep in "${DEPS[@]}"; do
            dep="${dep// /}"
            [ -z "$dep" ] && continue
            mkdir -p "prereqs/$dep"
            gh run download "${{ github.run_id }}" --name "$dep" --dir "prereqs/$dep" || true
          done
      - name: Check prerequisite status
        id: prereq_check
        if: inputs['cell-depends-on'] != '' && inputs['failure-reason'] == ''
        run: |
          FAILURE_REASON=""
          IFS=',' read -ra DEPS <<< "${{ inputs['cell-depends-on'] }}"
          for dep in "${DEPS[@]}"; do
            dep="${dep// /}"
            [ -z "$dep" ] && continue
            result_file=$(find "prereqs/$dep" -name 'result.v1.json' -path '*/meta/*' 2>/dev/null | head -1)
            if [ -z "$result_file" ]; then
              FAILURE_REASON="prerequisite $dep artifact missing or download failed"
              break
            fi
            STATUS=$(jq -r '.status // "unknown"' "$result_file")
            if [ "$STATUS" != "passed" ]; then
              FAILURE_REASON="prerequisite $dep had status: $STATUS"
              break
            fi
          done
          echo "prereq-failure-reason=$FAILURE_REASON" >> $GITHUB_OUTPUT
      - name: Emit blocked artifact (when prerequisite failed)
        id: blocked_cell
        if: inputs['failure-reason'] != '' || steps.prereq_check.outputs['prereq-failure-reason'] != ''
        run: |
          REASON="${{ inputs['failure-reason'] }}"
          if [ -z "$REASON" ]; then
            REASON="${{ steps.prereq_check.outputs['prereq-failure-reason'] }}"
          fi
          nu scripts/ocmts.nu ci emit-blocked \
            --scenario "${{ inputs.scenario }}" \
            --sender-platform "${{ inputs['sender-platform'] }}" \
            --sender-version "${{ inputs['sender-version'] }}" \
            --receiver-platform "${{ inputs['receiver-platform'] }}" \
            --receiver-version "${{ inputs['receiver-version'] }}" \
            --execution-id "${{ steps.cell.outputs['execution-id'] }}" \
            --failure-reason "$REASON" \
            --suite-id "${{ inputs['suite-id'] }}"
          echo "cell-status=blocked" >> $GITHUB_OUTPUT
      - name: Run cell (when no prerequisite failure)
        id: run_cell
        if: inputs['failure-reason'] == '' && steps.prereq_check.outputs['prereq-failure-reason'] == ''
        env:
          SUITE_ID: ${{ inputs['suite-id'] }}
          EXECUTION_ID: ${{ steps.cell.outputs['execution-id'] }}
        run: |
          if nu scripts/ocmts.nu services up run \
            --scenario "${{ inputs.scenario }}" \
            --sender-platform "${{ inputs['sender-platform'] }}" \
            --sender-version "${{ inputs['sender-version'] }}" \
            --receiver-platform "${{ inputs['receiver-platform'] }}" \
            --receiver-version "${{ inputs['receiver-version'] }}" \
            --suite-id "${{ inputs['suite-id'] }}" \
            --suite-kind suite \
            --execution-id "${{ steps.cell.outputs['execution-id'] }}"; then
            echo "cell-status=passed" >> $GITHUB_OUTPUT
          else
            echo "cell-status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
      - name: Pre-pull optimizer image
        id: prepull_optimizer
        if: always() && github.ref == 'refs/heads/{{placeholder:publish.branch.gate}}'
        continue-on-error: true
        run: |
          IMG=$(nu -c "use scripts/lib/images/resolve.nu [resolve-media-optimizer-image]; resolve-media-optimizer-image | print -n")
          docker pull "$IMG"
      - name: Optimize cell media
        id: optimize_media
        if: always() && github.ref == 'refs/heads/{{placeholder:publish.branch.gate}}'
        continue-on-error: true
        run: |
          nu scripts/ocmts.nu artifacts optimize-media \
            --raw-dir artifacts/ \
            --out-dir artifacts-optimized/
      - name: Upload optimized media artifact
        if: always() && github.ref == 'refs/heads/{{placeholder:publish.branch.gate}}'
        uses: actions/upload-artifact@v4
        with:
          name: optimized-media-${{ inputs['artifact-name'] }}
          path: artifacts-optimized/
          if-no-files-found: ignore
      - name: Upload cell artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs['artifact-name'] }}
          path: artifacts/
          if-no-files-found: warn
