# Generated by: {{placeholder:generator.command}}
# Do NOT edit by hand - regenerate with the command above.
# Site publish workflow.
#
# workflow_call: called by ci-matrix.yml after aggregate succeeds on the
#   publish branch. Caller must pass source-run-id (its own github.run_id)
#   so artifact downloads target the correct ci-matrix run.
#
# workflow_dispatch: manual rebuild. Resolves the latest successful
#   ci-matrix.yml run on the configured publish branch, downloads its
#   artifacts, and republishes the site.
#
# Jobs:
#   prepare         - resolve source run ID
#   aggregate-media - download optimized cell artifacts, aggregate, upload summary
#   build           - download raw aggregate + media summary, run site publish, upload pages artifact
#   deploy          - deploy built site to GitHub Pages

name: OCM Site Publish

on:
  workflow_call:
    inputs:
      source-run-id:
        description: 'Run ID to download artifacts from; caller passes github.run_id'
        type: string
        required: true
  workflow_dispatch:

jobs:
  prepare:
    runs-on: {{placeholder:runner.label}}
    outputs:
      source-run-id: ${{ steps.resolve.outputs['source-run-id'] }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Resolve artifact source run
        id: resolve
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "${{ inputs['source-run-id'] }}" ]; then
            RUN_ID=$(nu scripts/ocmts.nu ci resolve-source-run \
              --workflow {{placeholder:site.rebuild.source.workflow}} \
              --branch {{placeholder:publish.branch.gate}} \
              --run-id "${{ inputs['source-run-id'] }}")
          else
            RUN_ID=$(nu scripts/ocmts.nu ci resolve-source-run \
              --workflow {{placeholder:site.rebuild.source.workflow}} \
              --branch {{placeholder:publish.branch.gate}})
          fi
          echo "source-run-id=$RUN_ID" >> $GITHUB_OUTPUT

  aggregate-media:
    needs: [prepare]
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Probe optimizer image
        run: |
          nu scripts/ocmts.nu artifacts probe-optimizer
      - name: Download optimized media artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download "${{ needs['prepare'].outputs['source-run-id'] }}" \
            --pattern '{{placeholder:optimized.artifact.pattern}}' \
            --dir artifacts/optimized/
      - name: Aggregate optimized media
        run: |
          nu scripts/ocmts.nu artifacts aggregate-optimized-media \
            --scan-dir artifacts/optimized \
            --output-dir artifacts/optimized-summary/
      - name: Upload optimized media summary
        uses: actions/upload-artifact@v4
        with:
          name: {{placeholder:optimized.aggregate.artifact.name}}
          path: artifacts/optimized-summary/
          if-no-files-found: error

  build:
    needs: [prepare, aggregate-media]
    runs-on: {{placeholder:runner.label}}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nushell
        uses: {{placeholder:setup.nu.action}}
        with:
          version: '{{placeholder:nushell.version}}'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Download raw aggregate artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download "${{ needs['prepare'].outputs['source-run-id'] }}" \
            --name {{placeholder:raw.aggregate.artifact.name}} \
            --dir artifacts/suites/aggregated/
      - name: Extract aggregate archive
        run: |
          tar -x -I zstd -f artifacts/suites/aggregated/suite-artifacts.tar.zst
      - name: Download optimized media summary
        uses: actions/download-artifact@v4
        with:
          name: {{placeholder:optimized.aggregate.artifact.name}}
          path: artifacts/optimized-summary/
      - name: Publish site
        env:
          OCMTS_SITE_REPO_SLUG: ${{ vars.OCMTS_SITE_REPO_SLUG || '' }}
          OCMTS_SITE_REF: ${{ vars.OCMTS_SITE_REF || '' }}
          OCMTS_SITE_REPO_URL: ${{ vars.OCMTS_SITE_REPO_URL || '' }}
          ASTRO_BASE: {{placeholder:astro.base}}
          ASTRO_SITE: '{{placeholder:astro.site}}'
        run: |
          nu scripts/ocmts.nu site publish \
            --artifacts-root artifacts \
            --latest-suite \
            --optimized-media-dir artifacts/optimized-summary/
      - name: Upload built site
        uses: actions/upload-pages-artifact@v3
        with:
          path: {{placeholder:site.build.output.path}}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
