// Generated by `nu scripts/ocmts.nu matrix gen cypress`.
// Do not edit by hand.
export const matrixCellIds = [
  "contact-wayf__nextcloud-v34__nextcloud-v34",
] as const;
export type MatrixCellId = (typeof matrixCellIds)[number];
