base_url = "https://cs3org.github.io/ocm-test-suite"
title = "OCM Test Suite"
description = "Compatibility status of various file sharing and collaboration features across different platforms"
default_language = "en"

# Theme settings
theme = "PonderMatrix"
compile_sass = true

# Markdown settings
[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
