// Generated by `nu scripts/ocmts.nu matrix gen cypress`.
// Do not edit by hand.
export const matrixCellIds = [
  "login__nextcloud-v32",
  "login__nextcloud-v33",
  "login__nextcloud-v34",
  "login__ocis-v8",
  "login__ocmgo-v1",
  "login__opencloud-v6",
] as const;
export type MatrixCellId = (typeof matrixCellIds)[number];
