# Default values for Reva gateway
# ===============================
revad:
  ingress:
    enabled: true
    services:
      http:
        annotations:
          kubernetes.io/ingress.class: 'nginx'
      grpc:
        annotations:
          kubernetes.io/ingress.class: 'nginx'
  config:
    log:
      level: debug
    shared:
      jwt_secret: ocm-test-suite-test-123
    grpc:
      services:
        authprovider:
          auth_manager: nextcloud
        gateway:
          commit_share_to_storage_grant: false
          commit_share_to_storage_ref: true
          transfer_expires: 6
        ocmcore:
          driver: nextcloud
        ocmproviderauthorizer:
          drivers:
            json:
              verify_request_hostname: true
        ocmshareprovider:
          driver: nextcloud
        preferences: {}
        publicshareprovider:
          driver: memory
        storageprovider:
          driver: nextcloud
          expose_data_server: true
          enable_home_creation: true
        userprovider:
          driver: nextcloud
        usershareprovider:
          driver: memory
    http:
      services:
        dataprovider:
          driver: nextcloud
        ocdav:
          prefix: ocdav
        ocmd:
          prefix: ocm
        ocs:
          prefix: ocs
        prometheus: {}
        sysinfo: {}
      middlewares:
        cors: {}
        providerauthorizer:
          drivers:
            json:
              verify_request_hostname: true
