[shared]
gatewaysvc = "revad1.docker:19000"

[grpc]
address = "revad1.docker:19010"

[grpc.services.storageprovider]
driver = "ocmreceived"
mount_path = "/sciencemesh"
mount_id = "sciencemesh"
expose_data_server = true
data_server_url = "http://revad1.docker:19011/data"

[http]
address = "revad1.docker:19011"

[http.services.dataprovider]
driver = "ocmreceived"
