[log]
level = "debug"

[shared]
gatewaysvc = "revaoc1.docker:19000"
# gatewaycertfile = "/etc/revad/tls/revaoc1.crt"

# [registry]
# driver = "static"
#
# [registry.static]
# services = ["authprovider","userprovider"]
#
# [registry.static.authprovider]
# bearer = ["localhost:0123"]
# basic = ["localhost:1234"]
# publiclink = ["localhost:9876"]

[grpc]
address = "0.0.0.0:19000"
# certfile = "/etc/revad/tls/revaoc1.crt"
# keyfile = "/etc/revad/tls/revaoc1.key"

[grpc.services.gateway]
authregistrysvc = "revaoc1.docker:19000"
appprovidersvc = "revaoc1.docker:19000"
appregistry = "revaoc1.docker:19000"
storageregistrysvc = "revaoc1.docker:19000"
preferencessvc = "revaoc1.docker:19000"
userprovidersvc = "revaoc1.docker:19000"
usershareprovidersvc = "revaoc1.docker:19000"
publicshareprovidersvc = "revaoc1.docker:19000"
ocmcoresvc = "revaoc1.docker:19000"
ocmshareprovidersvc = "revaoc1.docker:19000"
ocminvitemanagersvc = "revaoc1.docker:19000"
ocmproviderauthorizersvc = "revaoc1.docker:19000"
commit_share_to_storage_grant = false
datagateway = "https://revaoc1.docker/data"
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "revaoc1.docker:19000"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = {"address" = "revaoc1.docker:19000"}
"00000000-0000-0000-0000-000000000000" = {"address" = "revaoc1.docker:19000"}

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "nextcloud"

[grpc.services.ocmcore.drivers.nextcloud]
webdav_host = "https://oc1.docker/"
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocminvitemanager]
driver = "json"
provider_domain = "revaoc1.docker"

[grpc.services.ocmshareprovider]
driver = "nextcloud"

[grpc.services.ocmshareprovider.drivers.nextcloud]
webdav_host = "https://oc1.docker/"
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.testnet.json"
verify_request_hostname = true

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.appprovider]
driver = "demo"
iopsecret = "testsecret"
wopiurl = "http://0.0.0.0:8880/"
wopibridgeurl = "http://localhost:8000/wopib"

[grpc.services.appregistry]
driver = "static"

[grpc.services.appregistry.static.rules]
"text/plain" = "revaoc1.docker:19000"
"text/markdown" = "revaoc1.docker:19000"
"application/compressed-markdown" = "revaoc1.docker:19000"
"application/vnd.oasis.opendocument.text" = "revaoc1.docker:19000"
"application/vnd.oasis.opendocument.spreadsheet" = "revaoc1.docker:19000"
"application/vnd.oasis.opendocument.presentation" = "revaoc1.docker:19000"

[grpc.services.storageprovider]
driver = "nextcloud"
expose_data_server = true
data_server_url = "https://revaoc1.docker/data"
enable_home_creation = true

[grpc.services.storageprovider.drivers.nextcloud]
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.authprovider]
auth_manager = "nextcloud"

[grpc.services.authprovider.auth_managers.nextcloud]
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.userprovider]
driver = "nextcloud"

[grpc.services.userprovider.drivers.nextcloud]
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http]
# enabled_services = ["ocmd","sciencemesh"]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:443"
certfile = "/etc/revad/tls/revaoc1.crt"
keyfile = "/etc/revad/tls/revaoc1.key"

[http.services.sciencemesh]

[http.services.dataprovider]
driver = "nextcloud"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.nextcloud]
endpoint = "https://oc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http.services.ocmd]
prefix = "ocm"

[http.services.ocmd.config]
host = "revaoc1.docker"
provider = "test-revaoc1"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.testnet.json"

[http.services.ocs]
prefix = "ocs"

[http.middlewares.cors]

# example data transfer service configuration
[grpc.services.datatx]
# rclone is the default data transfer driver
txdriver = "rclone"
# the shares,transfers db file (default: /var/tmp/reva/datatx-shares.json)
tx_shares_file = ""
# base folder of the data transfers (default: /home/DataTransfers)
data_transfers_folder = ""

# rclone data transfer driver
[grpc.services.datatx.txdrivers.rclone]
# rclone endpoint
endpoint = "http://rclone.docker"
# basic auth is used
auth_user = "rcloneuser"
auth_pass = "eilohtho9oTahsuongeeTh7reedahPo1Ohwi3aek"
auth_header = "x-access-token"
# the transfers(jobs) db file (default: /var/tmp/reva/datatx-transfers.json)
file = ""
# check status job interval in milliseconds
job_status_check_interval = 2000
# the job timeout in milliseconds (must be long enough for big transfers!)
job_timeout = 120000

[http.services.ocdav]
prefix = "ocdav"
# Rclone supports third-party copy push; for that to work with reva enable this setting
# enable_http_tpc = true
# The authentication scheme reva uses for the tpc push call (the call to Destination). 
# Follows the destination endpoint authentication method.
# Valid values:
#   "bearer" (default)    will result in header:   Authorization: "Bearer ...token..."
#   "x-access-token"      will result in header:   X-Access-Token: "...token..."
# If not set "bearer" is assumed
http_tpc_push_auth_header = "x-access-token"