# Cypress matrix generator tests.
# Covers: allowlist membership, sorted/deduped cell IDs, generator header,
# and --check drift detection.
# Run: nu scripts/tests/matrix/cypress-gen.nu

const SUITE_PATH = path self

use ../../lib/matrix/cypress-gen.nu [
    collect-flow-cell-ids
    generate-cypress-matrix
    check-cypress-matrix-files
]
use ../../lib/matrix/rules-gen.nu [load-matrix-rules]
use ../../lib/tests/assert.nu *
use ../../lib/tests/fixtures.nu [with-tmp-dir]
use ../../lib/tests/runner.nu [run-suite]

def repo-root [] {
    $SUITE_PATH | path dirname | path dirname | path dirname | path dirname
}

def ocmts-script [] {
    (repo-root) | path join "scripts/ocmts.nu"
}

def fixture-rules-with-duplicate-cell [] {
  {
    matrix: {
      login__nextcloud: {
        enabled: true,
        flow_id: "login",
        browsers: ["chrome"],
        sender: {platform: "nextcloud", version_lines: ["v34" "v34"]},
        receiver: null,
        mitm: false,
      },
    }
  }
}

def test-generate-cypress-matrix-includes-webapp-share [] {
    test-log "\n[test-generate-cypress-matrix-includes-webapp-share]"
    let rules = (load-matrix-rules (repo-root))
    let entries = (generate-cypress-matrix $rules)
    let flow_ids = ($entries | get flow_id)
    let webapp_entry = ($entries | where flow_id == "webapp-share" | first)
    [
        (assert-truthy ("webapp-share" in $flow_ids)
            "cypress generator allowlist includes webapp-share")
        (assert-truthy ($webapp_entry.content | str contains "webapp-share__nextcloud-v35__cernbox-v11")
            "webapp-share matrix content includes supported cernbox cell")
        (assert-truthy ($webapp_entry.content | str contains "webapp-share__nextcloud-v35__nextcloud-v35")
            "webapp-share matrix content includes supported nextcloud cell")
    ]
}

def test-collect-flow-cell-ids-sorted-deduped [] {
    test-log "\n[test-collect-flow-cell-ids-sorted-deduped]"
    let rules = (fixture-rules-with-duplicate-cell)
    let ids = (collect-flow-cell-ids $rules "login")
  [
    (assert-eq $ids ["login__nextcloud-v34"]
      "collect-flow-cell-ids dedupes duplicate version pairs and sorts by cell_id")
  ]
}

def test-gen-cypress-matrix-ts-header [] {
    test-log "\n[test-gen-cypress-matrix-ts-header]"
    let rules = (load-matrix-rules (repo-root))
    let webapp = (generate-cypress-matrix $rules | where flow_id == "webapp-share" | first)
    [
        (assert-truthy ($webapp.content | str starts-with "// Generated by `nu scripts/ocmts.nu matrix gen cypress`.")
            "webapp-share matrix.ts carries generator header command")
        (assert-truthy ($webapp.content | str contains "// Do not edit by hand.")
            "webapp-share matrix.ts carries do-not-edit banner")
    ]
}

def test-check-cypress-matrix-files-detects-drift [] {
    test-log "\n[test-check-cypress-matrix-files-detects-drift]"
    with-tmp-dir {|tmp|
        mkdir ($tmp | path join "cypress/e2e/webapp-share")
        let rules = (load-matrix-rules (repo-root))
        let expected = (generate-cypress-matrix $rules | where flow_id == "webapp-share" | first).content
        let drifted = ($expected | str replace "webapp-share__nextcloud-v35__cernbox-v11" "stale-cell-id")
        $drifted | save --force ($tmp | path join "cypress/e2e/webapp-share/matrix.ts")
        let results = (check-cypress-matrix-files $rules $tmp)
        let webapp = ($results | where flow_id == "webapp-share" | first)
        [
            (assert-truthy (not $webapp.ok)
                "check-cypress-matrix-files reports drift for stale webapp-share matrix.ts")
            (assert-eq $webapp.diff "content differs"
                "drift result explains content mismatch")
        ]
    }
}

def test-matrix-gen-cypress-check-passes-on-repo [] {
    test-log "\n[test-matrix-gen-cypress-check-passes-on-repo]"
    let out = (with-env {OCMTS_ROOT: (repo-root)} {
        ^nu (ocmts-script) matrix gen cypress --check | complete
    })
    [
        (assert-eq $out.exit_code 0
            "ocmts matrix gen cypress --check exits 0 on committed matrix files")
        (assert-string-contains $out.stdout "cypress matrix check: OK"
            "ocmts matrix gen cypress --check reports OK")
    ]
}

def main [] {
    test-log "=== matrix/cypress-gen tests ==="
    let results = (
        (test-generate-cypress-matrix-includes-webapp-share)
        | append (test-collect-flow-cell-ids-sorted-deduped)
        | append (test-gen-cypress-matrix-ts-header)
        | append (test-check-cypress-matrix-files-detects-drift)
        | append (test-matrix-gen-cypress-check-passes-on-repo)
    ) | flatten
    run-suite "matrix/cypress-gen" $SUITE_PATH $results
}
