// Generated by `nu scripts/ocmts.nu matrix gen cypress`.
// Do not edit by hand.
export const matrixCellIds = [
  "webapp-share__nextcloud-v35__cernbox-v11",
  "webapp-share__nextcloud-v35__nextcloud-v35",
] as const;
export type MatrixCellId = (typeof matrixCellIds)[number];
