name = "OCM Theme"
description = "A theme for the OCM Compatibility Matrix"
license = "MIT"
homepage = "https://github.com/pondersource/dev-stock"
min_version = "0.4.0"

[author]
name = "PonderSource"
homepage = "https://pondersource.com"

[extra] 