[shared]
gatewaysvc = "revad2.docker:17000"

[grpc]
address = "0.0.0.0:17000"

[grpc.services.gateway]
authregistrysvc = "revad2.docker:17000"
storageregistrysvc = "revad2.docker:17000"
preferencessvc = "revad2.docker:17000"
userprovidersvc = "revad2.docker:17000"
usershareprovidersvc = "revad2.docker:17000"
publicshareprovidersvc = "revad2.docker:17000"
ocmcoresvc = "revad2.docker:17000"
ocmshareprovidersvc = "revad2.docker:17000"
ocminvitemanagersvc = "revad2.docker:17000"
ocmproviderauthorizersvc = "revad2.docker:17000"
datagateway = "http://revad2.docker:17001/data"
transfer_expires = 6                         # give it a moment
commit_share_to_storage_grant = true
commit_share_to_storage_ref = true

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "revad2.docker:17000"
machine = "revad2.docker:17030"
ocmshares = "revad2.docker:17020"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = { "address" = "revad2.docker:17000" }
"123e4567-e89b-12d3-a456-426655440000" = { "address" = "revad2.docker:17000" }
"/sciencemesh" = { "address" = "revad2.docker:17010" }
"sciencemesh" = { "address" = "revad2.docker:17010" }
"/ocm" = { "address" = "revad2.docker:17020" }
"ocm" = { "address" = "revad2.docker:17020" }

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "json"

# Note that ocmcore and ocmshareprovider should use the same file for storing the shares.
[grpc.services.ocmcore.drivers.json]
file = "/var/tmp/reva/shares_server_2.json"

[grpc.services.ocminvitemanager]
driver = "json"
provider_domain = "cesnet.cz"

[grpc.services.ocminvitemanager.drivers.json]
file = "/var/tmp/reva/invites_server_2.json"

[grpc.services.ocmshareprovider]
driver = "json"
webdav_endpoint = "http://revad2.docker:17001"
provider_domain = "cesnet.cz"

[grpc.services.ocmshareprovider.drivers.json]
file = "/var/tmp/reva/shares_server_2.json"

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.storageprovider]
driver = "localhome"
mount_path = "/home"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://revad2.docker:17001/data"
enable_home_creation = true

[grpc.services.storageprovider.drivers.localhome]
user_layout = "{{.Username}}"

[grpc.services.authprovider]
auth_manager = "json"

[grpc.services.authprovider.auth_managers.json]
users = "users.demo.json"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "users.demo.json"

[http]
address = "0.0.0.0:17001"

[http.services.dataprovider]
driver = "localhome"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.localhome]
user_layout = "{{.Username}}"

[http.services.ocmd]

[http.services.ocmprovider]
provider = "reva@cesnet"
endpoint = "http://revad2.docker:17001"
enable_webapp = true
enable_datatx = true

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.demo.json"

[http.services.ocs]
prefix = "ocs"

[http.services.ocdav]

[http.middlewares.cors]
