[shared]
gatewaysvc = "revad2.docker:17000"

[grpc]
address = "revad2.docker:17010"

[grpc.services.storageprovider]
driver = "ocmreceived"
mount_path = "/sciencemesh"
mount_id = "sciencemesh"
expose_data_server = true
data_server_url = "http://revad2.docker:17011/data"

[http]
address = "revad2.docker:17011"

[http.services.dataprovider]
driver = "ocmreceived"
