[shared]
gatewaysvc = "revad2.docker:17000"

[grpc]
address = "revad2.docker:17030"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "machine-api-key"
gateway_addr = "revad2.docker:17000"
