[log]
level = "debug"
output = "/var/log/revad.log"

[shared]
gatewaysvc = "revanc1.docker:19000"
# gatewaycertfile = "/etc/revad/tls/revanc1.crt"

# [registry]
# driver = "static"
#
# [registry.static]
# services = ["authprovider","userprovider"]
#
# [registry.static.authprovider]
# bearer = ["localhost:0123"]
# basic = ["localhost:1234"]
# publiclink = ["localhost:9876"]

[grpc]
address = "0.0.0.0:19000"
# certfile = "/etc/revad/tls/revanc1.crt"
# keyfile = "/etc/revad/tls/revanc1.key"

[grpc.services.gateway]
authregistrysvc = "revanc1.docker:19000"
appprovidersvc = "revanc1.docker:19000"
appregistry = "revanc1.docker:19000"
storageregistrysvc = "revanc1.docker:19000"
preferencessvc = "revanc1.docker:19000"
userprovidersvc = "revanc1.docker:19000"
usershareprovidersvc = "revanc1.docker:19000"
publicshareprovidersvc = "revanc1.docker:19000"
ocmcoresvc = "revanc1.docker:19000"
ocmshareprovidersvc = "revanc1.docker:19000"
ocminvitemanagersvc = "revanc1.docker:19000"
ocmproviderauthorizersvc = "revanc1.docker:19000"
commit_share_to_storage_grant = false
datagateway = "https://revanc1.docker/data"
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "revanc1.docker:19000"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = {"address" = "revanc1.docker:19000"}
"00000000-0000-0000-0000-000000000000" = {"address" = "revanc1.docker:19000"}

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "nextcloud"

[grpc.services.ocmcore.drivers.nextcloud]
webdav_host = "https://nc1.docker/"
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocminvitemanager]
driver = "json"
provider_domain = "revanc1.docker"

[grpc.services.ocmshareprovider]
driver = "nextcloud"
provider_domain = "revanc1.docker"
webdav_endpoint = "https://nc1.docker/"

[grpc.services.ocmshareprovider.drivers.nextcloud]
webdav_host = "https://nc1.docker/"
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.testnet.json"
verify_request_hostname = true

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.appregistry]
driver = "static"

[grpc.services.storageprovider]
driver = "nextcloud"
expose_data_server = true
data_server_url = "https://revanc1.docker/data"
enable_home_creation = true

[grpc.services.storageprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.authprovider]
auth_manager = "nextcloud"

[grpc.services.authprovider.auth_managers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.userprovider]
driver = "nextcloud"

[grpc.services.userprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:443"
certfile = "/etc/revad/tls/revanc1.crt"
keyfile = "/etc/revad/tls/revanc1.key"

[http.services.sciencemesh]
invite_link_template = "{{.MeshDirectoryURL}}?token={{.Token}}&providerDomain=revanc1.docker"

[http.services.dataprovider]
driver = "nextcloud"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http.services.ocmd]
prefix = "ocm"

[http.services.ocmd.config]
host = "revanc1.docker"
provider = "test-revanc1"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.testnet.json"

[http.services.ocs]
prefix = "ocs"

[http.middlewares.cors]

# example data transfer service configuration
[grpc.services.datatx]
# rclone is the default data transfer driver
txdriver = "rclone"
# the shares,transfers db file (default: /var/tmp/reva/datatx-shares.json)
tx_shares_file = ""
# base folder of the data transfers (default: /home/DataTransfers)
data_transfers_folder = ""

# rclone data transfer driver
[grpc.services.datatx.txdrivers.rclone]
# rclone endpoint
endpoint = "http://rclone.docker"
# basic auth is used
auth_user = "rcloneuser"
auth_pass = "eilohtho9oTahsuongeeTh7reedahPo1Ohwi3aek"
auth_header = "x-access-token"
# the transfers(jobs) db file (default: /var/tmp/reva/datatx-transfers.json)
file = ""
# check status job interval in milliseconds
job_status_check_interval = 2000
# the job timeout in milliseconds (must be long enough for big transfers!)
job_timeout = 120000

[http.services.ocdav]
prefix = "ocdav"
# Rclone supports third-party copy push; for that to work with reva enable this setting
# enable_http_tpc = true
# The authentication scheme reva uses for the tpc push call (the call to Destination). 
# Follows the destination endpoint authentication method.
# Valid values:
#   "bearer" (default)    will result in header:   Authorization: "Bearer ...token..."
#   "x-access-token"      will result in header:   X-Access-Token: "...token..."
# If not set "bearer" is assumed
http_tpc_push_auth_header = "x-access-token"

[http.services.ocmprovider]
provider = "Pondersource dev-stock NC1"
endpoint = "https://revanc1.docker:19000"
webdav_root = "/remote.php/dav/ocm"
enable_webapp = true
enable_datatx = true

[grpc.services.appprovider]
driver = "wopi"
custom_mime_types_json = "custom-mime-types-demo.json"
mime_types = ["application/vnd.oasis.opendocument.text", "application/vnd.oasis.opendocument.spreadsheet", "application/vnd.oasis.opendocument.presentation", "text/rtf"]
app_provider_url = "localhost:19000"
language = "en-GB"

[http.services.appprovider]
insecure = true

[grpc.services.appprovider.drivers.wopi]
iop_secret = "hello"
wopi_url = "http://wopi.docker:8880/"
app_name = "Collabora"
app_url = "http://collabora.docker:9980"
app_int_url = "http://collabora.docker:9980"
