name: Basic Workflow for Testing

on:
  workflow_call:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World!
        run: echo "Hello, World!"
