name: OCM Test Invite link Ocis v5.0.9 to Cernbox v1.29.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   ocis
      sender_version:    v5.0.9
      receiver_platform: cernbox
      receiver_version:  v1.29.0
