name: OCM Test Invite link Nextcloud-sm v27.1.11 to Nextcloud-sm v27.1.11

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   nextcloud-sm
      sender_version:    v27.1.11
      receiver_platform: nextcloud-sm
      receiver_version:  v27.1.11
