name: OCM Test Invite link Nextcloud-sm v27.1.11-sm to Ocis v7.1.2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   nextcloud-sm
      sender_version:    v27.1.11-sm
      receiver_platform: ocis
      receiver_version:  v7.1.2
