name: OCM Test Invite link Nextcloud-sm v27.1.11-sm to Cernbox v1.29.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   nextcloud-sm
      sender_version:    v27.1.11-sm
      receiver_platform: cernbox
      receiver_version:  v1.29.0
