name: OCM Test Invite link Ocis v7.1.2 to Owncloud-sm v10.15.0-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   ocis
      sender_version:    v7.1.2
      receiver_platform: owncloud-sm
      receiver_version:  v10.15.0-sm
