name: OCM Test Invite link Opencloud v2.3.0 to Owncloud-sm v10.15.0-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   opencloud
      sender_version:    v2.3.0
      receiver_platform: owncloud-sm
      receiver_version:  v10.15.0-sm
