name: OCM Test Invite link Owncloud-sm v10.15.0-sm to Owncloud-sm v10.15.0-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   owncloud-sm
      sender_version:    v10.15.0-sm
      receiver_platform: owncloud-sm
      receiver_version:  v10.15.0-sm
