name: OCM Test Invite Link NC SM v27.1.11 to OC SM v10.15.0

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the specified branch and files.
  push:
    branches:
      - main
    paths:
      - "cypress/ocm-test-suite/**"
      - "dev/ocm-test-suite.sh"
      - "dev/ocm-test-suite/**"
  pull_request:
    branches:
      - main
    paths:
      - "cypress/ocm-test-suite/**"
      - "dev/ocm-test-suite.sh"
      - "dev/ocm-test-suite/**"
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  invite-link:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        sender: [
          {
            platform: nextcloud-sm,
            version: v27.1.11-sm
          },
        ]
        receiver: [
          {
            platform: owncloud-sm,
            version: v10.15.0-sm
          },
        ]

    # The OS to run tests on, (I believe for OCM testing OS is really not that important).
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Pull images.
        shell: bash
        run: |
          ./docker/pull/ocm-test-suite/${{ matrix.sender.platform }}.sh     ${{ matrix.sender.version }}
          ./docker/pull/ocm-test-suite/${{ matrix.receiver.platform }}.sh   ${{ matrix.receiver.version }}

      - name: Run tests.
        shell: bash
        run: ./dev/ocm-test-suite.sh invite-link ${{ matrix.sender.platform }} ${{ matrix.sender.version }} ci electron ${{ matrix.receiver.platform }} ${{ matrix.receiver.version }}

      - name: Upload Cypress video artifacts.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: invite-link from ${{ matrix.sender.platform }} ${{ matrix.sender.version }} to ${{ matrix.receiver.platform }} ${{ matrix.receiver.version }}
          path: ./cypress/ocm-test-suite/cypress/videos
