name: OCM Test Invite link Owncloud-sm v10.15.0 to Ocis v5.0.9

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   owncloud-sm
      sender_version:    v10.15.0
      receiver_platform: ocis
      receiver_version:  v5.0.9
