name: OCM Test Invite link Nextcloud-sm v27.1.11-sm to Owncloud-sm v10.15.0-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   nextcloud-sm
      sender_version:    v27.1.11-sm
      receiver_platform: owncloud-sm
      receiver_version:  v10.15.0-sm
