name: OCM Test Invite link Nextcloud-sm v27.1.11-sm to Opencloud v2.3.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   nextcloud-sm
      sender_version:    v27.1.11-sm
      receiver_platform: opencloud
      receiver_version:  v2.3.0
