name: OCM Test Invite link Ocis v5.0.9 to Nextcloud-sm v27.1.11-sm

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          invite-link
      sender_platform:   ocis
      sender_version:    v5.0.9
      receiver_platform: nextcloud-sm
      receiver_version:  v27.1.11-sm
