name: OCM Test Login Ocmstub v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   ocmstub
      sender_version:    v1.0.0
