name: OCM Test Login Nextcloud v32.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   nextcloud
      sender_version:    v32.0.0
