name: OCM Test Login Nextcloud v29.0.16

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   nextcloud
      sender_version:    v29.0.16
