name: OCM Test Login Cernbox v1.29.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   cernbox
      sender_version:    v1.29.0
