name: OCM Test Login Nextcloud v28.0.14

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   nextcloud
      sender_version:    v28.0.14
