name: OCM Test Login Ocis v5.0.9

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   ocis
      sender_version:    v5.0.9
