name: OCM Test Login Nextcloud v30.0.11

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   nextcloud
      sender_version:    v30.0.11
