name: OCM Test Login Opencloud v2.3.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   opencloud
      sender_version:    v2.3.0
