name: OCM Test Login Seafile v11.0.13

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          login
      sender_platform:   seafile
      sender_version:    v11.0.13
