name: ocm-test-suite
run-name: Open Cloud Mesh Test Suite

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - ocm

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull images
        shell: bash
        run: ./ci/ocm-test-suite-pull-images.sh

      - name: Initalize OCM tests dependencies
        shell: bash
        run: ./ci/ocm-test-suite-init-deps.sh

      - name: Run tests
        shell: bash
        run: ./ci/ocm-test-suite.sh chrome
