name: OCM Test Share with Nextcloud v32.0.0 to Ocmstub v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v32.0.0
      receiver_platform: ocmstub
      receiver_version:  v1.0.0
