name: OCM Test Share link Nextcloud v29.0.2 to Owncloud v10.15.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v29.0.2
      receiver_platform: owncloud
      receiver_version:  v10.15.0
