name: OCM Test Share with Owncloud v10.15.0 to Ocmstub v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   owncloud
      sender_version:    v10.15.0
      receiver_platform: ocmstub
      receiver_version:  v1.0.0
