name: OCM Test Share link Owncloud v10.15.0 to Nextcloud v29.0.2

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   owncloud
      sender_version:    v10.15.0
      receiver_platform: nextcloud
      receiver_version:  v29.0.2
