name: OCM Test Share link Nextcloud v27.1.11 to Nextcloud v28.0.14

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v27.1.11
      receiver_platform: nextcloud
      receiver_version:  v28.0.14
