name: OCM Test Share with Nextcloud v29.0.16 to Nextcloud v32.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v29.0.16
      receiver_platform: nextcloud
      receiver_version:  v32.0.0
