name: OCM Test Share with Nextcloud v27.1.11 to Nextcloud v27.1.11

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v27.1.11
      receiver_platform: nextcloud
      receiver_version:  v27.1.11
