name: OCM Test Share link Nextcloud v29.0.2 to Ocmstub v1.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v29.0.2
      receiver_platform: ocmstub
      receiver_version:  v1.0.0
