name: OCM Test Share link Nextcloud v28.0.14 to Nextcloud v32.0.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v28.0.14
      receiver_platform: nextcloud
      receiver_version:  v32.0.0
