name: OCM Test Share with Ocmstub v1.0.0 to Owncloud v10.15.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   ocmstub
      sender_version:    v1.0.0
      receiver_platform: owncloud
      receiver_version:  v10.15.0
