name: OCM Test Share link Nextcloud v32.0.0 to Owncloud v10.15.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v32.0.0
      receiver_platform: owncloud
      receiver_version:  v10.15.0
