name: OCM Test Share with Ocmstub v1.0.0 to Nextcloud v28.0.14

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   ocmstub
      sender_version:    v1.0.0
      receiver_platform: nextcloud
      receiver_version:  v28.0.14
