name: OCM Test Share with Seafile v11.0.13 to Seafile v11.0.13

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   seafile
      sender_version:    v11.0.13
      receiver_platform: seafile
      receiver_version:  v11.0.13
