name: OCM Test Share with Nextcloud v28.0.14 to Owncloud v10.15.0

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v28.0.14
      receiver_platform: owncloud
      receiver_version:  v10.15.0
