name: OCM Test Share with Nextcloud v29.0.2 to Nextcloud v28.0.14

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-with
      sender_platform:   nextcloud
      sender_version:    v29.0.2
      receiver_platform: nextcloud
      receiver_version:  v28.0.14
