name: OCM Test Share Link OC v10.14.0 to NC v27.1.10

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the specified branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  share-link:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        sender: [
          {
            platform: owncloud,
            version: v10.14.0
          },
        ]
        receiver: [
          {
            platform: nextcloud,
            version: v27.1.10
          },
        ]

    # The OS to run tests on, (I believe for OCM testing OS is really not that important).
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Pull images.
        shell: bash
        run: |
          ./docker/pull/ocm-test-suite/${{ matrix.sender.platform }}.sh     ${{ matrix.sender.version }}
          ./docker/pull/ocm-test-suite/${{ matrix.receiver.platform }}.sh   ${{ matrix.receiver.version }}

      - name: Run tests.
        shell: bash
        run: ./dev/ocm-test-suite.sh share-link ${{ matrix.sender.platform }} ${{ matrix.sender.version }} ci electron ${{ matrix.receiver.platform }} ${{ matrix.receiver.version }}

      - name: Upload Cypress video artifacts.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: share-link from ${{ matrix.sender.platform }} ${{ matrix.sender.version }} to ${{ matrix.receiver.platform }} ${{ matrix.receiver.version }}
          path: ./cypress/ocm-test-suite/cypress/videos
