name: OCM Test Share link Nextcloud v32.0.0 to Nextcloud v30.0.11

on:
  workflow_dispatch:

jobs:
  call-test-engine:
    uses: ./.github/workflows/tests-engine.yml
    with:
      scenario:          share-link
      sender_platform:   nextcloud
      sender_version:    v32.0.0
      receiver_platform: nextcloud
      receiver_version:  v30.0.11
