name: OCM Test Suite Engine
on:
  workflow_call:
    inputs:
      # login | share-link | share-with | invite-link
      scenario:              { type: string, required: true }
      sender_platform:       { type: string, required: true }
      sender_version:        { type: string, required: true }
      receiver_platform:     { type: string, required: false }
      receiver_version:      { type: string, required: false }

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Pull sender image
        run: ./docker/pull/ocm-test-suite/${{ inputs.sender_platform }}.sh ${{ inputs.sender_version }}

      - name: Pull receiver image
        if: ${{ inputs.receiver_platform != '' }}
        run: ./docker/pull/ocm-test-suite/${{ inputs.receiver_platform }}.sh ${{ inputs.receiver_version }}

      - name: Run OCM tests
        run: |
          SCENARIO="${{ inputs.scenario }}"
          if [ "$SCENARIO" = "login" ]; then
            ./dev/ocm-test-suite.sh login \
              ${{ inputs.sender_platform }} ${{ inputs.sender_version }} \
              ci electron
          else
            ./dev/ocm-test-suite.sh "$SCENARIO" \
              ${{ inputs.sender_platform }} ${{ inputs.sender_version }} \
              ci electron \
              ${{ inputs.receiver_platform }} ${{ inputs.receiver_version }}
          fi

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.scenario }}-${{ inputs.sender_platform }}-${{ inputs.sender_version }}${{ inputs.receiver_platform && format('-{0}-{1}', inputs.receiver_platform, inputs.receiver_version) || '' }}
          path: ./cypress/ocm-test-suite/cypress/videos
