name: OCM Tests Orchestrator

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the specified branch and files.
  push:
    branches:
      - main
    paths:
      - "cypress/ocm-test-suite/**"
      - "dev/ocm-test-suite.sh"
      - "dev/ocm-test-suite/**"
      - ".github/workflows/**"
      - "./scripts/github/**"
  pull_request:
    branches:
      - main
    paths:
      - "cypress/ocm-test-suite/**"
      - "dev/ocm-test-suite.sh"
      - "dev/ocm-test-suite/**"
      - ".github/workflows/**"
      - "./scripts/github/**"
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  orchestrate-tests:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get-sha.outputs.sha }}
      done: ${{ steps.run-tests.outputs.done }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: get-sha
        run: echo "sha=$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Set ref for workflow dispatch
        id: set-ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "ref=${{ github.head_ref }}" >> "${GITHUB_OUTPUT}"
          else
            echo "ref=${{ github.ref }}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Trigger and monitor test workflows
        id: run-tests
        uses: actions/github-script@v7
        env:
          WORKFLOW_REF: ${{ steps.set-ref.outputs.ref }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const orchestrateTests = require('./scripts/github/orchestrate-tests.js');
            context.ref = process.env.WORKFLOW_REF;

            try {
              // array of {name, conclusion}
              const results = await orchestrateTests(github, context, core);
              core.setOutput('done', 'true');
            } catch (err) {
              // Orchestrator itself failed - mark job red.
              core.setOutput('done', 'false');
              core.setFailed(`orchestrator error: ${err.message}`);
            }

  trigger-pages:
    needs: orchestrate-tests
    if: needs.orchestrate-tests.outputs.done == 'true'
    uses: ./.github/workflows/github-pages.yml
    with:
      sha: ${{ needs.orchestrate-tests.outputs.commit_sha }}
