[shared]
gatewaysvc = "revad1.docker:19000"

[grpc]
address = "revad1.docker:19030"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "machine-api-key"
gateway_addr = "revad1.docker:19000"
